### PR TITLE
fix "Invalid in command-line window" at #109

### PR DESCRIPTION
**Pull request by 3coma3**
Add a !silent so the error is not displayed

### CODE REVIEW

**Comment by camspiers** [comment]
I think it is probably right to suppress errors here, but I do wonder what is causing it.

**Comment by camspiers** [comment]
Thanks!

**Comment by 3coma3** [comment]
> I think it is probably right to suppress errors here, but I do wonder what is causing it.

It's `winnr()` and `wincmd`. If you try, with an arbitrary split layout, to run `:windo echo winnr()` or `:windo wincmd w`, they run without problem. However if you enter those while having a command line window open you get the error.

I think those functions just don't make sense with the command line window, it probably isn't a "normal" window like a split. This is my experimental conclusion though, I am no expert by any means.

**Comment by 3coma3** [comment]
And by the way, thanks a lot for this plugin! It makes vim very pleasant for my workflow, I often use complex layouts with many tabs and this + zoom.vim + [this little function I wrote](https://gist.github.com/3coma3/a0950bc79055fb9ded6363c554e162d0) really give me the best experience I could wish.

**Pull request merged**
